<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.8.2 on win32)" generated="20231123 11:23:10.788" rpa="false" schemaversion="4">
<suite id="s1" name="TestCase Num1" source="C:\Users\hp\PycharmProjects\Robot_General_Store\TestCases\TestCase_Num1.robot">
<test id="s1-t1" name="User Opens the Juno Application and Logs In" line="7">
<kw name="User Launches the Application" library="Operations">
<kw name="Open Application" library="AppiumLibrary">
<arg>http://localhost:4723/wd/hub</arg>
<arg>devicename=${Device_name}</arg>
<arg>platformName=${platform_name}</arg>
<arg>appPackage=${App_package}</arg>
<arg>appActivity=${App_activity}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20231123 11:23:34.252" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20231123 11:23:34.251" endtime="20231123 11:23:34.257"/>
</kw>
<msg timestamp="20231123 11:23:34.261" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20231123 11:23:34.262" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21131ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21131ms.
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)</msg>
<status status="FAIL" starttime="20231123 11:23:11.080" endtime="20231123 11:23:34.263"/>
</kw>
<status status="FAIL" starttime="20231123 11:23:11.079" endtime="20231123 11:23:34.263"/>
</kw>
<status status="FAIL" starttime="20231123 11:23:11.079" endtime="20231123 11:23:34.263">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21131ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21131ms.
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)</status>
</test>
<status status="FAIL" starttime="20231123 11:23:10.790" endtime="20231123 11:23:34.264"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="TestCase Num1">TestCase Num1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231123 11:23:34.261" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
